/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Board;
import model.Level;


/**
 *
 * @author Alexandre
 */
public class GameBoard extends JFrame {
    
    private static final int DEFAULT_WIDTH = 480;
    private static final int DEFAULT_HEIGHT = (DEFAULT_WIDTH / 12) * 9;
    private static final int SCALE = 2;
    private int changer = 1;
    private Board boardLevel;

    /**
     * Creates new form GamePanel
     */
    public GameBoard(Level levels) {
        boardLevel = new Board(levels.getLevelLayout(), 1, 5, 4);
        initComponents();
        this.setPreferredSize(new Dimension(DEFAULT_WIDTH * SCALE, DEFAULT_HEIGHT * SCALE));
        this.setMinimumSize(new Dimension(DEFAULT_WIDTH * SCALE, DEFAULT_HEIGHT * SCALE));
        this.setMaximumSize(new Dimension(DEFAULT_WIDTH * SCALE, DEFAULT_HEIGHT * SCALE));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        resetBtn.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = boardLevel;
        jPanel = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        getContentPane().add(board, java.awt.BorderLayout.CENTER);
        resetBtn.setText("Reset");
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(resetBtn)
                .addGap(0, 339, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(resetBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (board.isComplete()) {
            Object[] options = {"Yes", "No"};
            int choice = JOptionPane.showOptionDialog(this, "Deseja sair?", "Ganhou!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            
            
        } else {
            
            switch (evt.getKeyCode()) {
                case 37:
                    board.moveLeft();
                    board.player.setImage("PlayerSprites/Left" + changer);
                    break;
                case 39:
                    board.moveRight();
                    board.player.setImage("PlayerSprites/Right" + changer);
                    
                    break;
                case 38:
                    board.moveUp();
                    board.player.setImage("PlayerSprites/Up" + changer);
                    
                    break;
                case 40:
                    board.moveDown();
                    board.player.setImage("PlayerSprites/Down" + changer);
                    
                    break;
            }
            if (changer == 1) {
                changer = 2;
            } else {
                changer = 1;
            }
            board.repaint();
        }

    }//GEN-LAST:event_formKeyPressed

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_resetBtnMouseClicked
    
    private void formKeyReleased(java.awt.event.KeyEvent evt) {
//        switch (evt.getKeyCode()) {
//            case 37:
//                board.player.setImage("PlayerSprites/Left");
//                break;
//            case 39:
//                board.player.setImage("PlayerSprites/Right");
//                break;
//            case 38:
//                board.player.setImage("PlayerSprites/Up");
//                break;
//            case 40:
//                board.player.setImage("PlayerSprites/Down");
//                break;
//        }
//        board.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private model.Board board;
    private javax.swing.JPanel jPanel;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
